// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlWmVMev3X3Nk2BnRdNvx--7mUrcnzmwA',
    appId: '1:833182333424:web:f534c82cc6239a5d6ec535',
    messagingSenderId: '833182333424',
    projectId: 'appointmentbooking-73aab',
    authDomain: 'appointmentbooking-73aab.firebaseapp.com',
    storageBucket: 'appointmentbooking-73aab.firebasestorage.app',
    measurementId: 'G-HPSPZMBWM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbnkf6PIbADNbBtQWnDWEDXP0ZsPeg4FM',
    appId: '1:833182333424:android:ba0ee8a4a5033a4b6ec535',
    messagingSenderId: '833182333424',
    projectId: 'appointmentbooking-73aab',
    storageBucket: 'appointmentbooking-73aab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVgKYZf8WO6vjzc9a2TbQ0LmUwoYTDOAI',
    appId: '1:833182333424:ios:4ac181b111666c3f6ec535',
    messagingSenderId: '833182333424',
    projectId: 'appointmentbooking-73aab',
    storageBucket: 'appointmentbooking-73aab.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVgKYZf8WO6vjzc9a2TbQ0LmUwoYTDOAI',
    appId: '1:833182333424:ios:4ac181b111666c3f6ec535',
    messagingSenderId: '833182333424',
    projectId: 'appointmentbooking-73aab',
    storageBucket: 'appointmentbooking-73aab.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlWmVMev3X3Nk2BnRdNvx--7mUrcnzmwA',
    appId: '1:833182333424:web:8499852241e8581c6ec535',
    messagingSenderId: '833182333424',
    projectId: 'appointmentbooking-73aab',
    authDomain: 'appointmentbooking-73aab.firebaseapp.com',
    storageBucket: 'appointmentbooking-73aab.firebasestorage.app',
    measurementId: 'G-T61ZZ46TMS',
  );
}
